plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'io.scio'
version = '1.0.0'

android {
  namespace "expo.modules.sciogoogleauth"
}

dependencies {
  implementation "androidx.credentials:credentials:1.5.0"
  implementation "androidx.credentials:credentials-play-services-auth:1.5.0"
  implementation "com.google.android.libraries.identity.googleid:googleid:1.1.1"
}
